#!/bin/sh

set -eu

ENV_FILE=${ENV_FILE:-.env}
FORCE=0

usage() {
    echo "Usage: $0 [--force] [--print-host-ip] [--print-host-fqdn]"
}

detect_host_ip() {
    candidate=""

    if command -v ipconfig >/dev/null 2>&1; then
        candidate=$(ipconfig getifaddr en0 2>/dev/null || true)
        [ -n "$candidate" ] || candidate=$(ipconfig getifaddr en1 2>/dev/null || true)
    fi

    if [ -z "$candidate" ] && command -v ip >/dev/null 2>&1; then
        candidate=$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}' || true)
    fi

    if [ -z "$candidate" ] && command -v hostname >/dev/null 2>&1; then
        candidate=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
    fi

    if [ -z "$candidate" ] && command -v ifconfig >/dev/null 2>&1; then
        candidate=$(ifconfig 2>/dev/null | awk '/inet / && $2 != "127.0.0.1" {print $2; exit}' || true)
    fi

    [ -n "$candidate" ] || candidate="127.0.0.1"
    printf '%s' "$candidate"
}

detect_host_fqdn() {
    candidate=""

    if command -v hostname >/dev/null 2>&1; then
        candidate=$(hostname -f 2>/dev/null || true)
        [ -n "$candidate" ] || candidate=$(hostname 2>/dev/null || true)
    fi

    [ -n "$candidate" ] || candidate="localhost"
    printf '%s' "$candidate"
}

random_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return
    fi

    dd if=/dev/urandom bs=32 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n'
}

existing_value() {
    key=$1
    [ -f "$ENV_FILE" ] || return 0
    awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$ENV_FILE"
}

value_or_default() {
    key=$1
    default=$2
    existing=$(existing_value "$key")

    if [ "$FORCE" -eq 0 ] && [ -n "$existing" ]; then
        printf '%s' "$existing"
    else
        printf '%s' "$default"
    fi
}

secret_or_existing() {
    key=$1
    existing=$(existing_value "$key")

    if [ "$FORCE" -eq 0 ] && [ -n "$existing" ]; then
        printf '%s' "$existing"
    else
        random_secret
    fi
}

write_var() {
    key=$1
    value=$2
    printf '%s=%s\n' "$key" "$value" >> "$TMP_FILE"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --force)
            FORCE=1
            ;;
        --print-host-ip)
            detect_host_ip
            exit 0
            ;;
        --print-host-fqdn)
            detect_host_fqdn
            exit 0
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
    shift
done

HOST_IP_VALUE=${HOST_IP:-$(detect_host_ip)}
HOST_FQDN_VALUE=${HOST_FQDN:-$(detect_host_fqdn)}
PUBLIC_URL="https://${HOST_IP_VALUE}:8443"
ALLOWED_ORIGINS_VALUE="${PUBLIC_URL},https://localhost:8443,https://${HOST_FQDN_VALUE}:8443"

ENV_DIR=$(dirname "$ENV_FILE")
mkdir -p "$ENV_DIR"
TMP_FILE=$(mktemp "${ENV_FILE}.tmp.XXXXXX" 2>/dev/null || mktemp)

{
    printf '# Auto-generated by scripts/generate-env.sh\n'
    printf '# Safe for local development. Replace OAuth placeholders for Google and 42 login.\n'
    printf '\n'
} > "$TMP_FILE"

write_var NODE_ENV "$(value_or_default NODE_ENV production)"
write_var ENV_MODE "$(value_or_default ENV_MODE local-demo)"
write_var HOST "$(value_or_default HOST 0.0.0.0)"
write_var HOST_IP "$HOST_IP_VALUE"
write_var HOST_FQDN "$HOST_FQDN_VALUE"
write_var GATEWAY_PORT "$(value_or_default GATEWAY_PORT 3000)"
write_var AUTH_PORT "$(value_or_default AUTH_PORT 3001)"
write_var USER_PORT "$(value_or_default USER_PORT 3002)"
write_var MATCHMAKING_PORT "$(value_or_default MATCHMAKING_PORT 3003)"
write_var CHAT_PORT "$(value_or_default CHAT_PORT 3004)"
write_var CHAT_SERVICE_PORT "$(value_or_default CHAT_SERVICE_PORT 3004)"
write_var FRONTEND_PORT "$(value_or_default FRONTEND_PORT 5173)"
write_var ACCESS_COOKIE_NAME "$(value_or_default ACCESS_COOKIE_NAME access_token)"
write_var BCRYPT_SALT_ROUNDS "$(value_or_default BCRYPT_SALT_ROUNDS 10)"
write_var SKIP_RATE_LIMIT "$(value_or_default SKIP_RATE_LIMIT false)"

printf '\n' >> "$TMP_FILE"
write_var JWT_SECRET "$(secret_or_existing JWT_SECRET)"
write_var JWT_CHALLENGE_SECRET "$(secret_or_existing JWT_CHALLENGE_SECRET)"
write_var JWT_REFRESH_SECRET "$(secret_or_existing JWT_REFRESH_SECRET)"
write_var JWT_EXPIRES_IN "$(value_or_default JWT_EXPIRES_IN 24h)"
write_var REFRESH_TOKEN_EXPIRES_IN "$(value_or_default REFRESH_TOKEN_EXPIRES_IN 7d)"
write_var SERVICE_TOKEN "$(secret_or_existing SERVICE_TOKEN)"
write_var INTERNAL_SERVICE_SECRET "$(secret_or_existing INTERNAL_SERVICE_SECRET)"
write_var COOKIE_SECRET "$(secret_or_existing COOKIE_SECRET)"

printf '\n' >> "$TMP_FILE"
write_var AUTH_SERVICE_HOST "$(value_or_default AUTH_SERVICE_HOST auth-service)"
write_var USER_SERVICE_HOST "$(value_or_default USER_SERVICE_HOST user-service)"
write_var MATCHMAKING_SERVICE_HOST "$(value_or_default MATCHMAKING_SERVICE_HOST matchmaking-service)"
write_var CHAT_SERVICE_HOST "$(value_or_default CHAT_SERVICE_HOST chat-service)"
write_var AUTH_SERVICE_URL "$(value_or_default AUTH_SERVICE_URL http://auth-service:3001)"
write_var USER_SERVICE_URL "$(value_or_default USER_SERVICE_URL http://user-service:3002)"
write_var MATCHMAKING_SERVICE_URL "$(value_or_default MATCHMAKING_SERVICE_URL http://matchmaking-service:3003)"
write_var CHAT_SERVICE_URL "$(value_or_default CHAT_SERVICE_URL http://chat-service:3004)"
write_var GAME_SERVICE_URL "$(value_or_default GAME_SERVICE_URL http://game-server:3005)"
write_var FRONTEND_URL "$PUBLIC_URL"
write_var ALLOWED_ORIGINS "$ALLOWED_ORIGINS_VALUE"
write_var VITE_API_URL "$(value_or_default VITE_API_URL '')"

printf '\n' >> "$TMP_FILE"
write_var SQLITE_DB_AUTH_PATH "$(value_or_default SQLITE_DB_AUTH_PATH /app/db/users.sqlite)"
write_var DB_USER_SERVICE_PATH "$(value_or_default DB_USER_SERVICE_PATH /app/db/users.sqlite)"
write_var DB_MATCHMAKING_SERVICE_PATH "$(value_or_default DB_MATCHMAKING_SERVICE_PATH /app/db/matchmaking.sqlite)"
write_var SQLITE_MATCHMAKING_DB_PATH "$(value_or_default SQLITE_MATCHMAKING_DB_PATH /app/db/matchmaking.sqlite)"
write_var PICTURE_PATH "$(value_or_default PICTURE_PATH /app/picture)"

printf '\n' >> "$TMP_FILE"
write_var GOOGLE_CLIENT_ID "$(value_or_default GOOGLE_CLIENT_ID TODO_GOOGLE_CLIENT_ID)"
write_var GOOGLE_CLIENT_SECRET "$(value_or_default GOOGLE_CLIENT_SECRET TODO_GOOGLE_CLIENT_SECRET)"
write_var GOOGLE_REDIRECT_URI "$(value_or_default GOOGLE_REDIRECT_URI ${PUBLIC_URL}/auth/google/callback)"
write_var FORTYTWO_CLIENT_ID "$(value_or_default FORTYTWO_CLIENT_ID TODO_FORTYTWO_CLIENT_ID)"
write_var FORTYTWO_CLIENT_SECRET "$(value_or_default FORTYTWO_CLIENT_SECRET TODO_FORTYTWO_CLIENT_SECRET)"
write_var FORTYTWO_REDIRECT_URI "$(value_or_default FORTYTWO_REDIRECT_URI ${PUBLIC_URL}/auth/42/callback)"
write_var CALLBACK_URI "$(value_or_default CALLBACK_URI ${PUBLIC_URL}/auth/google/callback)"

mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"

printf '\033[32m%s\033[0m %s\n' "✓" "${ENV_FILE} généré"
printf '\033[2m%s\033[0m\n' "HOST_IP=${HOST_IP_VALUE} FRONTEND_URL=${PUBLIC_URL}"
printf '\033[33m%s\033[0m %s\n' "!" "Mode local-demo : les valeurs OAuth générées sont des placeholders."
printf '\033[2m%s\033[0m\n' "Fonctionnalités indisponibles sans vraies clés : connexion Google, connexion 42."
